{{ "{%" }} set package_name = "{{ cookiecutter.repo_name }}" {{ "%}" }}
{{ "{%" }} set import_name = "{{ cookiecutter.import_name }}" {{ "%}" }}
{%- raw %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9

test:
  imports:
    - {{ import_name }}
  requires:
    - pytest
{%- endraw %}

about:
  home: https://github.com/{{ cookiecutter.github_repo_group }}/{{ cookiecutter.repo_name }}
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: {{ cookiecutter.description }}
